### ISSUE TITLE
课程咨询

### ISSUE THREAD

**Issue by SeddonShen** [Emanual20/2021NKUCS-Compilers-Lab#1]
学长您好，我是来自西北工业大学大三的学生，最近想自学一下编译原理的这个实验课，也就是自己按照编译原理比赛的模式做一个编译器练练手。正好在搜索Github时发现贵校有相似度非常高的实验课程。请问这门实验有更多的学习资料吗，类似Gitbook或者其他的资料，您这个仓库是从lab4开始，因此我不知道前3个lab怎么进行学习，刚刚开始学编译还不太理解整个流程，希望得到更多的资料，或者说，南开大学的同学们是如何使用您的这个仓库进行试验课程的呢？

**Comment by Emanual20** [comment]
首先感谢对nkucs编译原理课程的关注 :)
lab1-lab3是用于给同学们探索gcc，了解lex和yacc的过程，和编译器的制作过程无关，从lab4-lab7是编译器的完整构建过程。
以下是2021年的实验指导书：
[构造词法分析器.pdf](https://github.com/Emanual20/2021NKUCS-Compilers-Lab/files/8339266/default.pdf)
[构建语法分析器.pdf](https://github.com/Emanual20/2021NKUCS-Compilers-Lab/files/8339269/default.pdf)
[类型检查&中间代码生成.pdf](https://github.com/Emanual20/2021NKUCS-Compilers-Lab/files/8339268/default.pdf)
[目标代码生成.pdf](https://github.com/Emanual20/2021NKUCS-Compilers-Lab/files/8339271/default.pdf)
课程初次改革，指导书在编写的过程中难免仓促出现问题，欢迎指正 :)

另外推荐一下北航软院的编译原理实验，[Gitbook](https://buaa-se-compiling.github.io/miniSysY-tutorial/)，感觉他们的实验梯度设计的会比我们的实验设计合理很多，讲解可能也会详细一点，是我们之后想改进学习的方向 :)

**Comment by SeddonShen** [comment]
贵校和BUAA的课程都非常不错，非常感谢您的解答！
